export const shows = [
  {
    date: "February 23, 2023",
    venue: "Brauer House",
    venueUrl:
      "https://www.eventbrite.com/o/brauer-house-amp-bhouse-live-18059974031",
    location: "Lombard, IL",
    ticketUrl:
      "https://www.eventbrite.com/e/van-halen-vs-acdc-ft-tributes-jump-black-angus-free-show-tickets-518170129807?aff=ebdsoporgprofile",
    image: null,
    socialLink: "",
    details: "Free Show w/ JUMP (Van Halen)",
  },
  {
    date: "March 04, 2023",
    venue: "Reggies",
    venueUrl: "https://www.reggieslive.com/2023/03/?post_type=show",
    location: "Chicago, IL",
    ticketUrl:
      "https://www.ticketweb.com/event/maiden-chicago-black-angus-judas-reggies-rock-club-tickets/12902365",
    image: null,
    socialLink: "",
    details: "w/ Maiden Chicago, Judas Rising and Phat Kiss",
  },
  {
    date: "March 11, 2023",
    venue: "Basecamp",
    venueUrl: "https://www.basecamppub.com/",
    location: "Lisle, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "",
  },
];

export const pastShows = [
  {
    date: "January 28, 2023",
    venue: "JJ Keylls",
    venueUrl: "",
    location: "Lansing, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "",
  },
  {
    date: "December 09, 2022",
    venue: "Roc Haus",
    venueUrl: "https://rochaus.com/",
    location: "Chicago, IL",
    ticketUrl:
      "https://wl.seetickets.us/event/Blackened-The-Ultimate-Metallica-Tribute/510026?afflky=Rochaus",
    image: null,
    socialLink: "https://fb.me/e/2zokkF0Wu",
    details: "Back to the one and only Roc Haus!",
  },
  {
    date: "October 22, 2022",
    venue: "Foundation",
    venueUrl: "",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "",
  },
  {
    date: "August 13, 2022",
    venue: "Retro on Roscoe Festival",
    venueUrl: "https://www.starevents.com/event/retro-on-roscoe/",
    location: "Roscoe Village - Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "2pm afternoon show!",
  },
  {
    date: "May 22, 2022",
    venue: "Thirsty Beaver",
    venueUrl: "https://www.thirstybeaverpubandgrub.com/",
    location: "Crestwood, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "3pm afternoon show!",
  },
  {
    date: "May 1, 2022",
    venue: "Reggies",
    venueUrl: "https://www.reggieslive.com/",
    location: "Chicago, IL",
    ticketUrl:
      "https://savetherocknroll.bigcartel.com/product/save-the-rock-n-roll-festival-3-day-pass-tickets-21-and-over-december-11-13-2020",
    image: null,
    socialLink: "https://www.facebook.com/events/620960512592784",
    details: "Save the Rock 'n Roll Fest - 1pm.",
  },
  {
    date: "April 23, 2022",
    venue: "Roc Haus",
    venueUrl: "https://rochaus.com/",
    location: "West Dundee, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/633812177921325",
    details: "Rockin the west burbs",
  },
  {
    date: "December 31, 2021",
    venue: "Live Wire Lounge",
    venueUrl: "http://theforgelive.com/",
    location: "Chicago, IL",
    ticketUrl:
      "https://wamitickets.com/e/125/new-years-eve-with-black-angus-turbonitro-dj-eddie-gobbo",
    image: null,
    socialLink: "https://www.facebook.com/events/718794552423735",
    details: "New Years Eve Show",
  },
  {
    date: "December 18, 2021",
    venue: "WC Social Club",
    venueUrl: "http://theforgelive.com/",
    location: "West Chicago, IL",
    ticketUrl:
      "https://skeletix.com/1376-diver-down-van-halen-tribute-the-wc-soc/",
    image: null,
    socialLink: "https://www.facebook.com/events/620960512592784",
    details: "w/ Diver Down (Van Halen) and Rat Pack (Ratt)",
  },
  {
    date: "August 18, 2021",
    venue: "Reggies on the Beach",
    venueUrl: "https://www.reggieslive.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "",
  },
  {
    date: "July 10, 2021",
    venue: "Flatts and Sharpe Music Festival",
    venueUrl: "https://www.flattsandsharpe.com/",
    location: "Sheridan & Columbia St. - Rogers Park - Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "Headlining Rogers Park's coolest festival by the lake",
  },
  {
    date: "May 22, 2021",
    venue: "The Forge",
    venueUrl: "http://theforgelive.com/",
    location: "Joliet, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "First show back!",
  },
  {
    date: "May 16th, 2020",
    venue: "Public House on Cicero",
    venueUrl: "https://www.publichouseoncicero.com/",
    location: "Crestwood, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "April 17th, 2020",
    venue: "Tailgaters",
    venueUrl: "https://www.tailgatersgrill.com/",
    location: "Bolingbrook, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "April 10th, 2020",
    venue: "HVAC Pub",
    venueUrl: "https://www.hvacpubwrigley.com/",
    location: "Chicago, IL - Wrigleyville",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details:
      "Post Cubs Cardinals game.  Black Angus starts in the 10th inning.",
  },
  {
    date: "March 14th, 2020",
    venue: "Live Wire Lounge",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "February 27, 2020",
    venue: "Firewater Saloon",
    venueUrl: "https://edisonpark.firewatersaloonchicago.com/",
    location: "Edison Park, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2565162720403475/",
  },
  {
    date: "Monday, January 6th, 2020",
    venue: "Private Party",
    venueUrl: "",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "Friday, December 27th, 2019",
    venue: "House of Blues Chicago",
    venueUrl: "https://www.houseofblues.com/chicago",
    location: "Chicago, IL",
    ticketUrl:
      "https://www.houseofblues.com/chicago/EventDetail?tmeventid=04005777252F07BC&offerid=115979",
    image: null,
    socialLink: "https://www.facebook.com/events/2464016177173365/",
  },
  {
    date: "Saturday, December 21st, 2019",
    venue: "Public House on Cicero",
    venueUrl: "https://www.publichouseoncicero.com/",
    location: "Crestwood, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2202566386717178/",
  },
  {
    date: "Friday, October 4th, 2019",
    venue: "Live Wire Lounge - Little John's Birthday Bash",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2422439924706152/",
  },
  {
    date: "Saturday, September 21st, 2019",
    venue: "Brauer house w/ Phat Kiss and Too Bad",
    venueUrl: "https://www.brauerhouse.com/",
    location: "Lombard, IL",
    ticketUrl:
      "https://www.eventbrite.com/e/black-angus-phat-kiss-too-bad-company-tickets-65936751599",
    image: null,
    socialLink: "https://www.facebook.com/events/340843310125045/",
  },
  {
    date: "Saturday, August 31st, 2019",
    venue: "HVAC Pub - Cubs Post Game - 4pm",
    venueUrl: "https://www.hvacpub.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "Thursday, August 8th, 2019",
    venue: "Reggies - Robby Birthday Bash",
    venueUrl: "https://www.reggieslive.com",
    location: "Chicago, IL",
    ticketUrl:
      "https://www.reggieslive.com/show/black-angus-a-tribute-to-ac-dc/",
    image: null,
    socialLink: "https://www.facebook.com/events/312829506288575/",
  },
  {
    date: "Friday, April 26th, 2019",
    venue: "HVAC Pub",
    venueUrl: "https://www.hvacpub.com/",
    location: "Chicago, IL",
    ticketUrl: "https://www.facebook.com/events/2060105220711141/",
    image: null,
    socialLink: "https://www.facebook.com/events/2060105220711141/",
  },
  {
    date: "Friday, April 5th, 2019",
    venue: "Live Wire Lounge",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "https://www.ticketfly.com/purchase/event/1787836",
    image: null,
    socialLink: "https://www.facebook.com/events/814722865572710/",
  },
];
