export const shows = [
  {
    date: "May 22, 2021",
    venue: "The Forge",
    venueUrl: "http://theforgelive.com/",
    location: "Joliet, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "First show back!",
  },
  {
    date: "July 10, 2021",
    venue: "Flatts and Sharpe Music Festival",
    venueUrl: "https://www.flattsandsharpe.com/",
    location: "Sheridan & Columbia St. - Rogers Park - Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details: "Headlining Rogers Park's coolest festival by the lake",
  },
];

export const pastShows = [
  {
    date: "May 16th, 2020",
    venue: "Public House on Cicero",
    venueUrl: "https://www.publichouseoncicero.com/",
    location: "Crestwood, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "April 17th, 2020",
    venue: "Tailgaters",
    venueUrl: "https://www.tailgatersgrill.com/",
    location: "Bolingbrook, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "April 10th, 2020",
    venue: "HVAC Pub",
    venueUrl: "https://www.hvacpubwrigley.com/",
    location: "Chicago, IL - Wrigleyville",
    ticketUrl: "",
    image: null,
    socialLink: "",
    details:
      "Post Cubs Cardinals game.  Black Angus starts in the 10th inning.",
  },
  {
    date: "March 14th, 2020",
    venue: "Live Wire Lounge",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "February 27, 2020",
    venue: "Firewater Saloon",
    venueUrl: "https://edisonpark.firewatersaloonchicago.com/",
    location: "Edison Park, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2565162720403475/",
  },
  {
    date: "Monday, January 6th, 2020",
    venue: "Private Party",
    venueUrl: "",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "Friday, December 27th, 2019",
    venue: "House of Blues Chicago",
    venueUrl: "https://www.houseofblues.com/chicago",
    location: "Chicago, IL",
    ticketUrl:
      "https://www.houseofblues.com/chicago/EventDetail?tmeventid=04005777252F07BC&offerid=115979",
    image: null,
    socialLink: "https://www.facebook.com/events/2464016177173365/",
  },
  {
    date: "Saturday, December 21st, 2019",
    venue: "Public House on Cicero",
    venueUrl: "https://www.publichouseoncicero.com/",
    location: "Crestwood, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2202566386717178/",
  },
  {
    date: "Friday, October 4th, 2019",
    venue: "Live Wire Lounge - Little John's Birthday Bash",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "https://www.facebook.com/events/2422439924706152/",
  },
  {
    date: "Saturday, September 21st, 2019",
    venue: "Brauer house w/ Phat Kiss and Too Bad",
    venueUrl: "https://www.brauerhouse.com/",
    location: "Lombard, IL",
    ticketUrl:
      "https://www.eventbrite.com/e/black-angus-phat-kiss-too-bad-company-tickets-65936751599",
    image: null,
    socialLink: "https://www.facebook.com/events/340843310125045/",
  },
  {
    date: "Saturday, August 31st, 2019",
    venue: "HVAC Pub - Cubs Post Game - 4pm",
    venueUrl: "https://www.hvacpub.com/",
    location: "Chicago, IL",
    ticketUrl: "",
    image: null,
    socialLink: "",
  },
  {
    date: "Thursday, August 8th, 2019",
    venue: "Reggies - Robby Birthday Bash",
    venueUrl: "https://www.reggieslive.com",
    location: "Chicago, IL",
    ticketUrl:
      "https://www.reggieslive.com/show/black-angus-a-tribute-to-ac-dc/",
    image: null,
    socialLink: "https://www.facebook.com/events/312829506288575/",
  },
  {
    date: "Friday, April 26th, 2019",
    venue: "HVAC Pub",
    venueUrl: "https://www.hvacpub.com/",
    location: "Chicago, IL",
    ticketUrl: "https://www.facebook.com/events/2060105220711141/",
    image: null,
    socialLink: "https://www.facebook.com/events/2060105220711141/",
  },
  {
    date: "Friday, April 5th, 2019",
    venue: "Live Wire Lounge",
    venueUrl: "http://livewireloungechicago.com/",
    location: "Chicago, IL",
    ticketUrl: "https://www.ticketfly.com/purchase/event/1787836",
    image: null,
    socialLink: "https://www.facebook.com/events/814722865572710/",
  },
];
